-- MySQL Script generated by MySQL Workbench
-- mié 18 sep 2019 10:25:35 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Revistas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Revistas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Revistas` ;
USE `Revistas` ;

-- -----------------------------------------------------
-- Table `Revistas`.`Cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Revistas`.`Cuenta` (
  `idCuenta` VARCHAR(15) NOT NULL,
  `saldo` DOUBLE NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`idCuenta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Revistas`.`Editor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Revistas`.`Editor` (
  `id_editor` INT NOT NULL AUTO_INCREMENT,
  `correo_electronico` VARCHAR(45) NULL,
  `numero_cuenta` VARCHAR(45) NULL,
  `fotografia` BLOB NULL,
  `nombre` VARCHAR(45) NULL,
  `password` LONGTEXT NULL,
  `id_cuenta` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_editor`),
  INDEX `fk_Editor_Cuenta1_idx` (`id_cuenta` ASC) VISIBLE,
  UNIQUE INDEX `id_cuenta_UNIQUE` (`id_cuenta` ASC) VISIBLE,
  CONSTRAINT `FK_CUENTA_EDITOR`
    FOREIGN KEY (`id_cuenta`)
    REFERENCES `Revistas`.`Cuenta` (`idCuenta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Revistas`.`Permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Revistas`.`Permisos` (
  `idPermiso` INT NOT NULL,
  `codigo_revista` INT NULL,
  `suscripciones` TINYINT NULL DEFAULT 1,
  `me_gusta` TINYINT NULL DEFAULT 1,
  `comentarios` TINYINT NULL DEFAULT 1,
  PRIMARY KEY (`idPermiso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Revistas`.`Costos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Revistas`.`Costos` (
  `idCosto` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `monto` DOUBLE NULL,
  PRIMARY KEY (`idCosto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Revistas`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Revistas`.`Categoria` (
  `idCategoria` INT NOT NULL,
  `descripcion` VARCHAR(20) NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Revistas`.`Revista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Revistas`.`Revista` (
  `codigo` INT NOT NULL,
  `edición` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  `etiquetas` VARCHAR(45) NULL,
  `path` VARCHAR(45) NULL,
  `cuota_suscripcion` DOUBLE NULL,
  `fecha_de_publicacion` DATE NULL,
  `id_editor` INT NOT NULL,
  `id_Permisos` INT NOT NULL,
  `costo_por_dia` INT NOT NULL,
  `id_Categoria` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_Revista_Editor1_idx` (`id_editor` ASC) VISIBLE,
  INDEX `fk_Revista_Permisos1_idx` (`id_Permisos` ASC) VISIBLE,
  INDEX `fk_Revista_Costos1_idx` (`costo_por_dia` ASC) VISIBLE,
  UNIQUE INDEX `edición_UNIQUE` (`edición` ASC) VISIBLE,
  INDEX `fk_Revista_Categoria1_idx` (`id_Categoria` ASC) VISIBLE,
  CONSTRAINT `FK_EDITOR_REVISTA`
    FOREIGN KEY (`id_editor`)
    REFERENCES `Revistas`.`Editor` (`id_editor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PERMISOS`
    FOREIGN KEY (`id_Permisos`)
    REFERENCES `Revistas`.`Permisos` (`idPermiso`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `FK_COSTOS_REVISTA`
    FOREIGN KEY (`costo_por_dia`)
    REFERENCES `Revistas`.`Costos` (`idCosto`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `FK_CATEGORIA`
    FOREIGN KEY (`id_Categoria`)
    REFERENCES `Revistas`.`Categoria` (`idCategoria`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Revistas`.`Comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Revistas`.`Comentario` (
  `idComentario` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `autor` INT NULL,
  `fecha_hora` DATETIME NULL,
  `codigo_revista` INT NOT NULL,
  PRIMARY KEY (`idComentario`),
  INDEX `fk_Comentario_Revista1_idx` (`codigo_revista` ASC) VISIBLE,
  CONSTRAINT `FK_COMENTARIO_REVISTA`
    FOREIGN KEY (`codigo_revista`)
    REFERENCES `Revistas`.`Revista` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Revistas`.`Sistema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Revistas`.`Sistema` (
  `idSistema` INT NOT NULL,
  `porcentaje_de_ganancia` INT NULL,
  PRIMARY KEY (`idSistema`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Revistas`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Revistas`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `no_cuenta` VARCHAR(15) NULL,
  `nombre` VARCHAR(45) NULL,
  `correo_electronico` VARCHAR(45) NULL,
  `fotografia` BLOB NULL,
  `hobbies` VARCHAR(45) NULL,
  `gustos` VARCHAR(45) NULL,
  `password` LONGTEXT NULL,
  `id_cuenta` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `correo_electronico_UNIQUE` (`correo_electronico` ASC) VISIBLE,
  INDEX `fk_Usuario_Cuenta1_idx` (`id_cuenta` ASC) VISIBLE,
  UNIQUE INDEX `id_cuenta_UNIQUE` (`id_cuenta` ASC) VISIBLE,
  CONSTRAINT `FK_CUENTA_USUARIO`
    FOREIGN KEY (`id_cuenta`)
    REFERENCES `Revistas`.`Cuenta` (`idCuenta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Revistas`.`Administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Revistas`.`Administrador` (
  `idAdministrador` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `password` LONGTEXT NULL,
  `fecha_de_creacion` VARCHAR(45) NULL,
  `idSistema` INT NOT NULL,
  PRIMARY KEY (`idAdministrador`),
  INDEX `fk_Administrador_Sistema1_idx` (`idSistema` ASC) VISIBLE,
  CONSTRAINT `FK_SISTEMA`
    FOREIGN KEY (`idSistema`)
    REFERENCES `Revistas`.`Sistema` (`idSistema`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Revistas`.`Suscripcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Revistas`.`Suscripcion` (
  `idSuscripcion` INT NOT NULL,
  `estado` TINYINT NULL,
  `mes` INT NULL,
  `anio` INT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `codigo_revista` INT NOT NULL,
  PRIMARY KEY (`idSuscripcion`),
  INDEX `fk_Suscripcion_Usuario1_idx` (`idUsuario` ASC) VISIBLE,
  INDEX `fk_Suscripcion_Revista1_idx` (`codigo_revista` ASC) VISIBLE,
  CONSTRAINT `FK_SUSCRIPTOR`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `Revistas`.`Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_REVISTA`
    FOREIGN KEY (`codigo_revista`)
    REFERENCES `Revistas`.`Revista` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Revistas`.`MeGusta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Revistas`.`MeGusta` (
  `idMeGusta` INT NOT NULL,
  `codigo_revista` INT NULL,
  `edicion_revista` INT NULL,
  `usuario` INT NULL,
  `fecha_hora` DATETIME NULL,
  `codigo_revista` INT NOT NULL,
  PRIMARY KEY (`idMeGusta`),
  INDEX `fk_MeGusta_Revista1_idx` (`codigo_revista` ASC) VISIBLE,
  CONSTRAINT `FK_ME_GUSTA_REVISTA`
    FOREIGN KEY (`codigo_revista`)
    REFERENCES `Revistas`.`Revista` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
